SELECT
    A.AUTHOR_ID,
    AU.AUTHOR_NAME,
    A.CATEGORY,
    A.TOTAL_SALES
FROM
    (
     SELECT 
        B.AUTHOR_ID, 
        B.CATEGORY, 
        SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
     FROM 
        BOOK_SALES AS BS
            JOIN BOOK AS B ON BS.BOOK_ID = B.BOOK_ID
     WHERE 
        BS.SALES_DATE LIKE '2022-01%'
     GROUP BY 
        1, 2
    ) 
    AS A JOIN AUTHOR AS AU ON A.AUTHOR_ID = AU.AUTHOR_ID
ORDER BY
    1, 3 DESC