# WITH TEMP AS (
#     SELECT
#         C.CAR_ID,
#         CAR_TYPE,
#         DAILY_FEE,
#         DATEDIFF(END_DATE, START_DATE) + 1 AS PERIOD,
#         CASE
#             WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
#             WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
#             WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
#             ELSE '7일 미만'
#         END AS 'DURATION_TYPE'
#     FROM
#         CAR_RENTAL_COMPANY_CAR AS C
#         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS R
#             ON C.CAR_ID = R.CAR_ID
#     WHERE
#         CAR_TYPE IN ('세단', 'SUV') AND
#         START_DATE >= '2022-11-01' AND END_DATE <= '2022-11-30'
# )

# SELECT
#     CAR_ID,
#     T.CAR_TYPE,
#     FLOOR(
#         (DAILY_FEE * (100 - (IFNULL(DISCOUNT_RATE, 0))) / 100) * PERIOD
#     ) AS FEE
# FROM
#     TEMP AS T
#     LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
#         ON T.CAR_TYPE = D.CAR_TYPE AND T.DURATION_TYPE = D.DURATION_TYPE
# WHERE
#     FLOOR(
#         (DAILY_FEE * (100 - (IFNULL(DISCOUNT_RATE, 0))) / 100) * PERIOD
#     ) BETWEEN 500000 AND 1999999
# ORDER BY
#     FEE DESC,
#     CAR_TYPE,
#     CAR_ID DESC;

WITH AVAILABLE_CARS AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('세단', 'SUV')
    AND CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30'
        AND END_DATE >= '2022-11-01'
    )
),
PLAN AS (
    SELECT 
        C.CAR_ID,
        C.CAR_TYPE,
        C.DAILY_FEE,
        '30일 이상' AS DURATION_TYPE,
        FLOOR(C.DAILY_FEE * 30 * (100 - IFNULL(D.DISCOUNT_RATE, 0)) / 100) AS FEE
    FROM AVAILABLE_CARS C
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
        ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'
)
SELECT
    CAR_ID,
    CAR_TYPE,
    FEE
FROM PLAN
WHERE FEE BETWEEN 500000 AND 1999999
ORDER BY
    FEE DESC,
    CAR_TYPE ASC,
    CAR_ID DESC;
