WITH RECURSIVE PARENT AS (
    
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, (P.GENERATION + 1) AS GENERATION
    FROM ECOLI_DATA AS E
        JOIN PARENT AS P
            ON E.PARENT_ID = P.ID
)

SELECT 
    COUNT(*) AS "COUNT", GENERATION
FROM 
    PARENT
WHERE
    ID NOT IN (SELECT PARENT_ID
               FROM PARENT
               WHERE PARENT_ID IS NOT NULL)
GROUP BY 
    GENERATION
ORDER BY 
    GENERATION