WITH RECURSIVE GENERATION AS (
    
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION 
    
    SELECT A.ID, A.PARENT_ID, (B.GENERATION + 1) AS GENERATION
    FROM ECOLI_DATA AS A, GENERATION AS B
    WHERE A.PARENT_ID = B.ID
)

SELECT 
    COUNT(*) AS "COUNT", GENERATION
FROM 
    GENERATION
WHERE
    ID NOT IN (SELECT PARENT_ID
               FROM GENERATION
               WHERE PARENT_ID IS NOT NULL)
GROUP BY 
    GENERATION
ORDER BY 
    GENERATION