SELECT
    A.PRODUCT_ID,
    A.PRODUCT_NAME,
    A.PRICE * B.AMOUNT AS TOTAL_SALES
FROM
    FOOD_PRODUCT A,
    (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
     FROM FOOD_ORDER
     WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
     GROUP BY PRODUCT_ID
    ) B
WHERE
    A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC, PRODUCT_ID