WITH TEMP AS (
    SELECT
        HISTORY_ID,
        CAR_TYPE,
        DAILY_FEE,
        DATEDIFF(END_DATE, START_DATE) + 1 AS 'PERIOD',
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE '7일 미만'
        END AS 'DURATION_TYPE'
    FROM 
        CAR_RENTAL_COMPANY_CAR AS C
    JOIN
        CAR_RENTAL_COMPANY_RENTAL_HISTORY AS R
        ON C.CAR_ID = R.CAR_ID
    WHERE 
        CAR_TYPE = '트럭'
)

SELECT
    HISTORY_ID,
    FLOOR((DAILY_FEE / 100 * (100 - (IFNULL(DISCOUNT_RATE, 0)))) * PERIOD) AS FEE
FROM 
    TEMP AS T
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON T.CAR_TYPE = P.CAR_TYPE
    AND T.DURATION_TYPE = P.DURATION_TYPE
ORDER BY
    FEE DESC,
    HISTORY_ID DESC;
