SELECT
    A.FLAVOR
FROM
    FIRST_HALF A
        JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
              FROM JULY 
              GROUP BY FLAVOR)
          B ON A.FLAVOR = B.FLAVOR
ORDER BY
    A.TOTAL_ORDER + B.TOTAL DESC
LIMIT 3