SELECT user.USER_ID, user.NICKNAME, sum(board.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS board
JOIN USED_GOODS_USER AS user ON board.WRITER_ID = user.USER_ID
WHERE STATUS = 'DONE'
GROUP BY board.WRITER_ID HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;