WITH 
GRADE_SCORE_SUM AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE_SUM
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
),
GRADE_MAX_SCORE AS (
    SELECT MAX(SCORE_SUM) AS MAX_SCORE
    FROM GRADE_SCORE_SUM
)
SELECT
    GSS.SCORE_SUM AS SCORE,
    EMP.EMP_NO,
    EMP.EMP_NAME,
    EMP.POSITION,
    EMP.EMAIL
FROM HR_EMPLOYEES AS EMP
JOIN GRADE_SCORE_SUM AS GSS ON EMP.EMP_NO = GSS.EMP_NO
JOIN GRADE_MAX_SCORE AS GMS ON GSS.SCORE_SUM = GMS.MAX_SCORE