WITH 
GRADE_SUM AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE_SUM
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
    ORDER BY SCORE_SUM DESC
    LIMIT 1
)
SELECT
    G.SCORE_SUM AS SCORE,
    G.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM HR_EMPLOYEES AS E
JOIN GRADE_SUM AS G ON E.EMP_NO = G.EMP_NO