SELECT
    CASE
        WHEN GROUP_CONCAT(S.CATEGORY) LIKE '%Front End%' AND
             GROUP_CONCAT(S.NAME) LIKE '%Python%' THEN "A"            
        WHEN GROUP_CONCAT(S.NAME) LIKE '%C#%' THEN "B"        
        WHEN GROUP_CONCAT(S.CATEGORY) LIKE '%Front End%' THEN "C"
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM
    DEVELOPERS AS D
        JOIN SKILLCODES AS S ON D.SKILL_CODE & S.CODE
GROUP BY
    ID, EMAIL
    HAVING GRADE IS NOT NULL
ORDER BY
    1, 2

# SELECT
#     *
# FROM
#     DEVELOPERS AS D
#         JOIN SKILLCODES AS S ON D.SKILL_CODE & S.CODE
# ORDER BY ID